### ISSUE TITLE
The Copy parent Hub Keeps Loading and does not load

### ISSUE THREAD

**Issue by baronpankaj** [simonetodisco/azure-devops-copy-parent#3]
The Copy parent Hub Keeps Loading and does not load.

![image](https://user-images.githubusercontent.com/6840023/127223758-35cbb9b6-3ad4-4a01-9f02-5c72f73ddce2.png)

**Comment by simonetodisco** [comment]
Hi @baronpankaj, I wasn’t to reproduce your bug. Can you post me the errors from the browser console? Are you using the AD on premise version?

**Comment by baronpankaj** [comment]
Please mark it as resolved as it is not occurring anymore
